version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew build -x test
      - store_artifacts:
          path: build/grazi/plugin/reports
          destination: reports

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew :plugin:test
      - store_artifacts:
          path: build/plugin/reports

  gui-test:
    machine:
      enabled: true
      environment:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    working_directory: ~
    steps:
      - checkout
      - run:
          name: Start GUI tests
          command: ./gradlew :gui-tests:test
      - store_artifacts:
          path: build/gui-tests/reports
      - store_artifacts:
          path: build/gui-tests/idea-sandbox/system/log
      - store_artifacts:
          path: build/gui-tests/idea-sandbox/system/event-log
      - store_artifacts:
          path: gui-tests/guitest.log
  release:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew :plugin:publishPlugin -x test
workflows:
  version: 2
  build:
    jobs:
      - build
      - test
      - gui-test
  release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /dev-.*/
                - /stable-.*/
      - test:
          filters:
            branches:
              only:
                - /dev-.*/
                - /stable-.*/
      - approve-release:
          type: approval
          requires:
            - build
            - test
      - release:
          requires:
            - approve-release

