version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew build
  release:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew build publishPlugin
workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - build
      - approve-release:
          type: approval
          requires:
            - build
      - release:
          requires:
            - approve-release
