version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew build -x test
      - store_artifacts:
          path: build/grazi/plugin/reports
          destination: reports
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew :plugin:test
      - run: ./gradlew :gui-tests:guiTest
      - store_artifacts:
          path: build/grazi/gui-tests/reports
          destination: reports
  release:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~
    steps:
      - checkout
      - run: ./gradlew :plugin:publishPlugin
workflows:
  version: 2
  build:
    jobs:
      - build
      - test
  release:
    jobs:
      - build
      - approve-release:
          type: approval
          requires:
            - build
      - release:
          requires:
            - approve-release
